name: sync
services:
  db: 
    image: postgres:15
    container_name: sync_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7 
    container_name: sync_redis

  syncbeats:
    image: sync_image
    build:
      context: .
    container_name: syncbeats_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command:
      bash -c "alembic revision --autogenerate && alembic upgrade head && gunicorn syncbeats.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000"
    ports:
      - 8000:8000
