name: "syncbeat"
services:
  db: 
    image: postgres:16.3
    container_name: sync_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7 
    container_name: sync_redis

  syncbeats:
    image: sync_image
    build:
      context: .
    container_name: syncbeats_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command: ["/syncbeats/docker/app.sh"]
    ports:
      - 9000:8000
