"""create likes table

Revision ID: 089a93fe879e
Revises: f9f9b03d944c
Create Date: 2024-05-17 19:57:06.967891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089a93fe879e'
down_revision: Union[str, None] = 'f9f9b03d944c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_column('likes', 'user_id')
    # ### end Alembic commands ###
