"""Users modification migration

Revision ID: 419145a835f8
Revises: 723a5e0515b8
Create Date: 2024-05-15 14:42:30.715947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419145a835f8'
down_revision: Union[str, None] = '723a5e0515b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('holidays_count', sa.Integer(), nullable=False))
    op.drop_column('users', 'holidays')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('holidays', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'holidays_count')
    # ### end Alembic commands ###
