"""Add likes relationship to users

Revision ID: f5cc59f8e1c5
Revises: 73e82896edc6
Create Date: 2024-05-17 20:10:07.207702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5cc59f8e1c5'
down_revision: Union[str, None] = '73e82896edc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
